baseURL = "https://orz-ai.github.io/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "Gang's Blog"
theme = "gblog"

# SEO设置
enableRobotsTXT = true
enableSitemap = true
canonifyURLs = true

# 作者信息
[author]
  name = "Gang"
  email = "deepincode@qq.com"

# 站点参数
[params]
  description = "个人博客网站 - 分享技术、知识和生活感悟"
  keywords = ["博客", "技术", "生活", "编程", "Go语言", "Hugo"]
  mainSections = ["posts"]
  dateFormat = "2006-01-02"
  
  # SEO相关设置
  images = ["images/hero-bg.jpg"] # 默认社交分享图片
  # 社交媒体链接
  [params.social]
    github = "https://github.com/orz-ai"
    twitter = "https://twitter.com/xxx"
    weibo = "https://weibo.com/xxx"
  
  # 文章设置
  [params.post]
    featuredImageField = "featuredImage" # 特色图片字段名
    readingTime = true # 显示阅读时间

# 菜单配置
[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "photos"
    name = "照片墙"
    url = "/photos/"
    weight = 3
  [[menu.main]]
    identifier = "timeline"
    name = "时间线"
    url = "/timeline/"
    weight = 4

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 5

# 分页设置
[pagination]
  enable = true
  perPage = 10

# Markdown渲染设置
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = false
    style = "github"
    tabWidth = 4
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
